version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  api:
    build: .
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./data:/app/data

  # Optional: Caddy reverse proxy with HTTPS (edit Caddyfile with your domain)
  # caddy:
  #   image: caddy:2
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #   depends_on:
  #     - api

volumes:
  ollama:

